services:
  - type: web
    name: peerlink-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    
  - type: web
    name: peerlink-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    plan: free
    dockerCommand: npm start
    envVars:
      - key: BACKEND_URL
        fromService:
          name: peerlink-backend
          type: web
          property: host
